# syntax=docker/dockerfile:1.4

FROM --platform=linux/amd64 golang:1.22.4-bookworm AS builder

ARG PLUGIN_PACKAGE

WORKDIR /app

COPY ./plugin_go.mod /app/go.mod
COPY ./_plugins/${PLUGIN_PACKAGE}.go /app

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=amd64

RUN go clean -modcache
RUN go mod tidy -compat=1.22.4
RUN go build -buildmode=plugin -o ${PLUGIN_PACKAGE}.so ${PLUGIN_PACKAGE}.go

FROM scratch AS releaser
ARG PLUGIN_PACKAGE
COPY --link --from=builder /app/${PLUGIN_PACKAGE}.so /
