# syntax=docker/dockerfile:1.4

FROM --platform=linux/amd64 golang:1.22.4-bookworm AS builder

ARG PLUGIN_GO_FILE
ARG PLUGIN_SO_FILE

WORKDIR /app

COPY ./go.mod /app/go.mod
COPY ./_plugins/${PLUGIN_GO_FILE} /app

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=amd64

RUN go clean -modcache
RUN go mod tidy -compat=1.22.4
RUN go build -buildmode=plugin -o ${PLUGIN_SO_FILE} ${PLUGIN_GO_FILE}

FROM scratch AS releaser
ARG PLUGIN_SO_FILE
COPY --link --from=builder /app/${PLUGIN_SO_FILE} /
