version: '3'

dotenv: ['.env']

tasks:

  docker-build:
    cmds:
      - >-
        docker buildx build --no-cache --file=Dockerfile
        --output={{.USER_WORKING_DIR}}/bin --target=releaser {{.USER_WORKING_DIR}}

  go-fmt:
    cmds:
      - gofumpt -l -w .

  local-build:
    dotenv: ['.env']
    cmds:
      - task: go-fmt
      - >-
        go build -a
        -o bin/$GRPC_PROXY_BIN_NAME
        {{if .VERBOSE}}-v -a{{end}}
        main.go

  local-dist:
    cmds:
      - task: build
        vars:
          VERBOSE: true
