// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_tasks_v2beta2_cloudtaskspb "cloud.google.com/go/cloudtasks/apiv2beta2/cloudtaskspb"
	google_iam_v1_iampb "cloud.google.com/go/iam/apiv1/iampb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.tasks.v2beta2.CloudTasks", "cloudtasks.googleapis.com")
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/AcknowledgeTask", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.AcknowledgeTaskRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/AcknowledgeTask", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/CancelLease", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.CancelLeaseRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/CancelLease", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Task)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/CreateQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.CreateQueueRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/CreateQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Queue)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/CreateTask", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.CreateTaskRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/CreateTask", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Task)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/DeleteQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.DeleteQueueRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/DeleteQueue", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/DeleteTask", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.DeleteTaskRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/DeleteTask", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.GetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/GetQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.GetQueueRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/GetQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Queue)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/GetTask", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.GetTaskRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/GetTask", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Task)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/LeaseTasks", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.LeaseTasksRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/LeaseTasks", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.LeaseTasksResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/ListQueues", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.ListQueuesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/ListQueues", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.ListQueuesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/ListTasks", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.ListTasksRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/ListTasks", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.ListTasksResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/PauseQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.PauseQueueRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/PauseQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Queue)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/PurgeQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.PurgeQueueRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/PurgeQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Queue)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/RenewLease", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.RenewLeaseRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/RenewLease", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Task)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/ResumeQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.ResumeQueueRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/ResumeQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Queue)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/RunTask", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.RunTaskRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/RunTask", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Task)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.SetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/UpdateQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.UpdateQueueRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/UpdateQueue", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.Queue)(nil)).Elem())
	method2RequestType.Store("google.cloud.tasks.v2beta2.CloudTasks/UploadQueueYaml", reflect.TypeOf((*google_cloud_tasks_v2beta2_cloudtaskspb.UploadQueueYamlRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tasks.v2beta2.CloudTasks/UploadQueueYaml", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
}
