// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_security_publicca_v1_publiccapb "cloud.google.com/go/security/publicca/apiv1/publiccapb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.security.publicca.v1.PublicCertificateAuthorityService", "publicca.googleapis.com")
	method2RequestType.Store("google.cloud.security.publicca.v1.PublicCertificateAuthorityService/CreateExternalAccountKey", reflect.TypeOf((*google_cloud_security_publicca_v1_publiccapb.CreateExternalAccountKeyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.publicca.v1.PublicCertificateAuthorityService/CreateExternalAccountKey", reflect.TypeOf((*google_cloud_security_publicca_v1_publiccapb.ExternalAccountKey)(nil)).Elem())
}
