// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_talent_v4beta1_talentpb "cloud.google.com/go/talent/apiv4beta1/talentpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.talent.v4beta1.JobService", "jobs.googleapis.com")
	method2RequestType.Store("google.cloud.talent.v4beta1.JobService/BatchCreateJobs", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.BatchCreateJobsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4beta1.JobService/BatchCreateJobs", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.talent.v4beta1.JobService/BatchDeleteJobs", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.BatchDeleteJobsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4beta1.JobService/BatchDeleteJobs", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.talent.v4beta1.JobService/BatchUpdateJobs", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.BatchUpdateJobsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4beta1.JobService/BatchUpdateJobs", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.talent.v4beta1.JobService/CreateJob", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.CreateJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4beta1.JobService/CreateJob", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.Job)(nil)).Elem())
	method2RequestType.Store("google.cloud.talent.v4beta1.JobService/DeleteJob", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.DeleteJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4beta1.JobService/DeleteJob", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.talent.v4beta1.JobService/GetJob", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.GetJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4beta1.JobService/GetJob", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.Job)(nil)).Elem())
	method2RequestType.Store("google.cloud.talent.v4beta1.JobService/ListJobs", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.ListJobsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4beta1.JobService/ListJobs", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.ListJobsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.talent.v4beta1.JobService/SearchJobs", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.SearchJobsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4beta1.JobService/SearchJobs", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.SearchJobsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.talent.v4beta1.JobService/SearchJobsForAlert", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.SearchJobsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4beta1.JobService/SearchJobsForAlert", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.SearchJobsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.talent.v4beta1.JobService/UpdateJob", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.UpdateJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4beta1.JobService/UpdateJob", reflect.TypeOf((*google_cloud_talent_v4beta1_talentpb.Job)(nil)).Elem())
}
