// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_vision_v1p3beta1_product_search_servicepb "google.golang.org/genproto/googleapis/cloud/vision/v1p3beta1"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.vision.v1p3beta1.ProductSearch", "vision.googleapis.com")
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/AddProductToProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.AddProductToProductSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/AddProductToProductSet", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/CreateProduct", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.CreateProductRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/CreateProduct", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.Product)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/CreateProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.CreateProductSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/CreateProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ProductSet)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/CreateReferenceImage", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.CreateReferenceImageRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/CreateReferenceImage", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ReferenceImage)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/DeleteProduct", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.DeleteProductRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/DeleteProduct", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/DeleteProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.DeleteProductSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/DeleteProductSet", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/DeleteReferenceImage", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.DeleteReferenceImageRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/DeleteReferenceImage", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/GetProduct", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.GetProductRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/GetProduct", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.Product)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/GetProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.GetProductSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/GetProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ProductSet)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/GetReferenceImage", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.GetReferenceImageRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/GetReferenceImage", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ReferenceImage)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/ImportProductSets", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ImportProductSetsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/ImportProductSets", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/ListProductSets", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ListProductSetsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/ListProductSets", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ListProductSetsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/ListProducts", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ListProductsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/ListProducts", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ListProductsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/ListProductsInProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ListProductsInProductSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/ListProductsInProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ListProductsInProductSetResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/ListReferenceImages", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ListReferenceImagesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/ListReferenceImages", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ListReferenceImagesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/RemoveProductFromProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.RemoveProductFromProductSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/RemoveProductFromProductSet", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/UpdateProduct", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.UpdateProductRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/UpdateProduct", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.Product)(nil)).Elem())
	method2RequestType.Store("google.cloud.vision.v1p3beta1.ProductSearch/UpdateProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.UpdateProductSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.vision.v1p3beta1.ProductSearch/UpdateProductSet", reflect.TypeOf((*google_cloud_vision_v1p3beta1_product_search_servicepb.ProductSet)(nil)).Elem())
}
