// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_contentwarehouse_v1_document_schema_servicepb "google.golang.org/genproto/googleapis/cloud/contentwarehouse/v1"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService", "contentwarehouse.googleapis.com")
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService/CreateDocumentSchema", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_schema_servicepb.CreateDocumentSchemaRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService/CreateDocumentSchema", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_schema_servicepb.DocumentSchema)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService/DeleteDocumentSchema", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_schema_servicepb.DeleteDocumentSchemaRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService/DeleteDocumentSchema", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService/GetDocumentSchema", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_schema_servicepb.GetDocumentSchemaRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService/GetDocumentSchema", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_schema_servicepb.DocumentSchema)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService/ListDocumentSchemas", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_schema_servicepb.ListDocumentSchemasRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService/ListDocumentSchemas", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_schema_servicepb.ListDocumentSchemasResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService/UpdateDocumentSchema", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_schema_servicepb.UpdateDocumentSchemaRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentSchemaService/UpdateDocumentSchema", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_schema_servicepb.DocumentSchema)(nil)).Elem())
}
