// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_dataform_v1alpha2_dataformpb "cloud.google.com/go/dataform/apiv1alpha2/dataformpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.dataform.v1alpha2.Dataform", "dataform.googleapis.com")
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/CancelWorkflowInvocation", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.CancelWorkflowInvocationRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/CancelWorkflowInvocation", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/CommitWorkspaceChanges", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.CommitWorkspaceChangesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/CommitWorkspaceChanges", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/CreateCompilationResult", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.CreateCompilationResultRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/CreateCompilationResult", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.CompilationResult)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/CreateRepository", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.CreateRepositoryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/CreateRepository", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.Repository)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/CreateWorkflowInvocation", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.CreateWorkflowInvocationRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/CreateWorkflowInvocation", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.WorkflowInvocation)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/CreateWorkspace", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.CreateWorkspaceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/CreateWorkspace", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.Workspace)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/DeleteRepository", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.DeleteRepositoryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/DeleteRepository", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/DeleteWorkflowInvocation", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.DeleteWorkflowInvocationRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/DeleteWorkflowInvocation", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/DeleteWorkspace", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.DeleteWorkspaceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/DeleteWorkspace", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/FetchFileDiff", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.FetchFileDiffRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/FetchFileDiff", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.FetchFileDiffResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/FetchFileGitStatuses", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.FetchFileGitStatusesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/FetchFileGitStatuses", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.FetchFileGitStatusesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/FetchGitAheadBehind", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.FetchGitAheadBehindRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/FetchGitAheadBehind", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.FetchGitAheadBehindResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/FetchRemoteBranches", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.FetchRemoteBranchesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/FetchRemoteBranches", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.FetchRemoteBranchesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/GetCompilationResult", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.GetCompilationResultRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/GetCompilationResult", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.CompilationResult)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/GetRepository", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.GetRepositoryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/GetRepository", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.Repository)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/GetWorkflowInvocation", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.GetWorkflowInvocationRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/GetWorkflowInvocation", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.WorkflowInvocation)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/GetWorkspace", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.GetWorkspaceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/GetWorkspace", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.Workspace)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/InstallNpmPackages", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.InstallNpmPackagesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/InstallNpmPackages", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.InstallNpmPackagesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/ListCompilationResults", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ListCompilationResultsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/ListCompilationResults", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ListCompilationResultsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/ListRepositories", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ListRepositoriesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/ListRepositories", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ListRepositoriesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/ListWorkflowInvocations", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ListWorkflowInvocationsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/ListWorkflowInvocations", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ListWorkflowInvocationsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/ListWorkspaces", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ListWorkspacesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/ListWorkspaces", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ListWorkspacesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/MakeDirectory", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.MakeDirectoryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/MakeDirectory", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.MakeDirectoryResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/MoveDirectory", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.MoveDirectoryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/MoveDirectory", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.MoveDirectoryResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/MoveFile", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.MoveFileRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/MoveFile", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.MoveFileResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/PullGitCommits", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.PullGitCommitsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/PullGitCommits", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/PushGitCommits", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.PushGitCommitsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/PushGitCommits", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/QueryCompilationResultActions", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.QueryCompilationResultActionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/QueryCompilationResultActions", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.QueryCompilationResultActionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/QueryDirectoryContents", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.QueryDirectoryContentsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/QueryDirectoryContents", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.QueryDirectoryContentsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/QueryWorkflowInvocationActions", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.QueryWorkflowInvocationActionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/QueryWorkflowInvocationActions", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.QueryWorkflowInvocationActionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/ReadFile", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ReadFileRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/ReadFile", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ReadFileResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/RemoveDirectory", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.RemoveDirectoryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/RemoveDirectory", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/RemoveFile", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.RemoveFileRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/RemoveFile", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/ResetWorkspaceChanges", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.ResetWorkspaceChangesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/ResetWorkspaceChanges", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/UpdateRepository", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.UpdateRepositoryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/UpdateRepository", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.Repository)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataform.v1alpha2.Dataform/WriteFile", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.WriteFileRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataform.v1alpha2.Dataform/WriteFile", reflect.TypeOf((*google_cloud_dataform_v1alpha2_dataformpb.WriteFileResponse)(nil)).Elem())
}
