// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_contentwarehouse_v1_contentwarehousepb "cloud.google.com/go/contentwarehouse/apiv1/contentwarehousepb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.contentwarehouse.v1.PipelineService", "contentwarehouse.googleapis.com")
	method2RequestType.Store("google.cloud.contentwarehouse.v1.PipelineService/RunPipeline", reflect.TypeOf((*google_cloud_contentwarehouse_v1_contentwarehousepb.RunPipelineRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.PipelineService/RunPipeline", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
