// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_iam_v2beta_policypb "google.golang.org/genproto/googleapis/iam/v2beta"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.iam.v2beta.Policies", "iam.googleapis.com")
	method2RequestType.Store("google.iam.v2beta.Policies/CreatePolicy", reflect.TypeOf((*google_iam_v2beta_policypb.CreatePolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.iam.v2beta.Policies/CreatePolicy", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.iam.v2beta.Policies/DeletePolicy", reflect.TypeOf((*google_iam_v2beta_policypb.DeletePolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.iam.v2beta.Policies/DeletePolicy", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.iam.v2beta.Policies/GetPolicy", reflect.TypeOf((*google_iam_v2beta_policypb.GetPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.iam.v2beta.Policies/GetPolicy", reflect.TypeOf((*google_iam_v2beta_policypb.Policy)(nil)).Elem())
	method2RequestType.Store("google.iam.v2beta.Policies/ListPolicies", reflect.TypeOf((*google_iam_v2beta_policypb.ListPoliciesRequest)(nil)).Elem())
	method2ResponseType.Store("google.iam.v2beta.Policies/ListPolicies", reflect.TypeOf((*google_iam_v2beta_policypb.ListPoliciesResponse)(nil)).Elem())
	method2RequestType.Store("google.iam.v2beta.Policies/UpdatePolicy", reflect.TypeOf((*google_iam_v2beta_policypb.UpdatePolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.iam.v2beta.Policies/UpdatePolicy", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
