// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_gkehub_v1_servicepb "google.golang.org/genproto/googleapis/cloud/gkehub/v1"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.gkehub.v1.GkeHub", "gkehub.googleapis.com")
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/CreateFeature", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.CreateFeatureRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/CreateFeature", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/CreateMembership", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.CreateMembershipRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/CreateMembership", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/DeleteFeature", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.DeleteFeatureRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/DeleteFeature", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/DeleteMembership", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.DeleteMembershipRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/DeleteMembership", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/GenerateConnectManifest", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.GenerateConnectManifestRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/GenerateConnectManifest", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.GenerateConnectManifestResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/GetFeature", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.GetFeatureRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/GetFeature", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.Feature)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/GetMembership", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.GetMembershipRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/GetMembership", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.Membership)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/ListFeatures", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.ListFeaturesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/ListFeatures", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.ListFeaturesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/ListMemberships", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.ListMembershipsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/ListMemberships", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.ListMembershipsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/UpdateFeature", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.UpdateFeatureRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/UpdateFeature", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1.GkeHub/UpdateMembership", reflect.TypeOf((*google_cloud_gkehub_v1_servicepb.UpdateMembershipRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1.GkeHub/UpdateMembership", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
