// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_tpu_v1_tpupb "cloud.google.com/go/tpu/apiv1/tpupb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.tpu.v1.Tpu", "tpu.googleapis.com")
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/CreateNode", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.CreateNodeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/CreateNode", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/DeleteNode", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.DeleteNodeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/DeleteNode", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/GetAcceleratorType", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.GetAcceleratorTypeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/GetAcceleratorType", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.AcceleratorType)(nil)).Elem())
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/GetNode", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.GetNodeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/GetNode", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.Node)(nil)).Elem())
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/GetTensorFlowVersion", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.GetTensorFlowVersionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/GetTensorFlowVersion", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.TensorFlowVersion)(nil)).Elem())
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/ListAcceleratorTypes", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.ListAcceleratorTypesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/ListAcceleratorTypes", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.ListAcceleratorTypesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/ListNodes", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.ListNodesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/ListNodes", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.ListNodesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/ListTensorFlowVersions", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.ListTensorFlowVersionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/ListTensorFlowVersions", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.ListTensorFlowVersionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/ReimageNode", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.ReimageNodeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/ReimageNode", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/StartNode", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.StartNodeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/StartNode", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.tpu.v1.Tpu/StopNode", reflect.TypeOf((*google_cloud_tpu_v1_tpupb.StopNodeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.tpu.v1.Tpu/StopNode", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
