// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_osconfig_v1_osconfigpb "cloud.google.com/go/osconfig/apiv1/osconfigpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.osconfig.v1.OsConfigService", "osconfig.googleapis.com")
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/CancelPatchJob", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.CancelPatchJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/CancelPatchJob", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.PatchJob)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/CreatePatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.CreatePatchDeploymentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/CreatePatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.PatchDeployment)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/DeletePatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.DeletePatchDeploymentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/DeletePatchDeployment", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/ExecutePatchJob", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.ExecutePatchJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/ExecutePatchJob", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.PatchJob)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/GetPatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.GetPatchDeploymentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/GetPatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.PatchDeployment)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/GetPatchJob", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.GetPatchJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/GetPatchJob", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.PatchJob)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/ListPatchDeployments", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.ListPatchDeploymentsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/ListPatchDeployments", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.ListPatchDeploymentsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/ListPatchJobInstanceDetails", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.ListPatchJobInstanceDetailsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/ListPatchJobInstanceDetails", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.ListPatchJobInstanceDetailsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/ListPatchJobs", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.ListPatchJobsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/ListPatchJobs", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.ListPatchJobsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/PausePatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.PausePatchDeploymentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/PausePatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.PatchDeployment)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/ResumePatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.ResumePatchDeploymentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/ResumePatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.PatchDeployment)(nil)).Elem())
	method2RequestType.Store("google.cloud.osconfig.v1.OsConfigService/UpdatePatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.UpdatePatchDeploymentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.osconfig.v1.OsConfigService/UpdatePatchDeployment", reflect.TypeOf((*google_cloud_osconfig_v1_osconfigpb.PatchDeployment)(nil)).Elem())
}
