// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_backupdr_v1_backupdrpb "cloud.google.com/go/backupdr/apiv1/backupdrpb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.backupdr.v1.BackupDR", "backupdr.googleapis.com")
	method2RequestType.Store("google.cloud.backupdr.v1.BackupDR/CreateManagementServer", reflect.TypeOf((*google_cloud_backupdr_v1_backupdrpb.CreateManagementServerRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.backupdr.v1.BackupDR/CreateManagementServer", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.backupdr.v1.BackupDR/DeleteManagementServer", reflect.TypeOf((*google_cloud_backupdr_v1_backupdrpb.DeleteManagementServerRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.backupdr.v1.BackupDR/DeleteManagementServer", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.backupdr.v1.BackupDR/GetManagementServer", reflect.TypeOf((*google_cloud_backupdr_v1_backupdrpb.GetManagementServerRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.backupdr.v1.BackupDR/GetManagementServer", reflect.TypeOf((*google_cloud_backupdr_v1_backupdrpb.ManagementServer)(nil)).Elem())
	method2RequestType.Store("google.cloud.backupdr.v1.BackupDR/ListManagementServers", reflect.TypeOf((*google_cloud_backupdr_v1_backupdrpb.ListManagementServersRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.backupdr.v1.BackupDR/ListManagementServers", reflect.TypeOf((*google_cloud_backupdr_v1_backupdrpb.ListManagementServersResponse)(nil)).Elem())
}
