// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_iam_v1_iampb "cloud.google.com/go/iam/apiv1/iampb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_securitycenter_v1beta1_securitycenterpb "cloud.google.com/go/securitycenter/apiv1beta1/securitycenterpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.securitycenter.v1beta1.SecurityCenter", "securitycenter.googleapis.com")
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/CreateFinding", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.CreateFindingRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/CreateFinding", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.Finding)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/CreateSource", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.CreateSourceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/CreateSource", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.Source)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.GetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/GetOrganizationSettings", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.GetOrganizationSettingsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/GetOrganizationSettings", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.OrganizationSettings)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/GetSource", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.GetSourceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/GetSource", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.Source)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/GroupAssets", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.GroupAssetsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/GroupAssets", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.GroupAssetsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/GroupFindings", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.GroupFindingsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/GroupFindings", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.GroupFindingsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/ListAssets", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.ListAssetsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/ListAssets", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.ListAssetsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/ListFindings", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.ListFindingsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/ListFindings", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.ListFindingsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/ListSources", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.ListSourcesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/ListSources", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.ListSourcesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/RunAssetDiscovery", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.RunAssetDiscoveryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/RunAssetDiscovery", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/SetFindingState", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.SetFindingStateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/SetFindingState", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.Finding)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.SetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/UpdateFinding", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.UpdateFindingRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/UpdateFinding", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.Finding)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/UpdateOrganizationSettings", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.UpdateOrganizationSettingsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/UpdateOrganizationSettings", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.OrganizationSettings)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/UpdateSecurityMarks", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.UpdateSecurityMarksRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/UpdateSecurityMarks", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.SecurityMarks)(nil)).Elem())
	method2RequestType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/UpdateSource", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.UpdateSourceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.securitycenter.v1beta1.SecurityCenter/UpdateSource", reflect.TypeOf((*google_cloud_securitycenter_v1beta1_securitycenterpb.Source)(nil)).Elem())
}
