// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.longrunning.Operations", "longrunning.googleapis.com")
	method2RequestType.Store("google.longrunning.Operations/CancelOperation", reflect.TypeOf((*google_longrunning_longrunningpb.CancelOperationRequest)(nil)).Elem())
	method2ResponseType.Store("google.longrunning.Operations/CancelOperation", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.longrunning.Operations/DeleteOperation", reflect.TypeOf((*google_longrunning_longrunningpb.DeleteOperationRequest)(nil)).Elem())
	method2ResponseType.Store("google.longrunning.Operations/DeleteOperation", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.longrunning.Operations/GetOperation", reflect.TypeOf((*google_longrunning_longrunningpb.GetOperationRequest)(nil)).Elem())
	method2ResponseType.Store("google.longrunning.Operations/GetOperation", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.longrunning.Operations/ListOperations", reflect.TypeOf((*google_longrunning_longrunningpb.ListOperationsRequest)(nil)).Elem())
	method2ResponseType.Store("google.longrunning.Operations/ListOperations", reflect.TypeOf((*google_longrunning_longrunningpb.ListOperationsResponse)(nil)).Elem())
	method2RequestType.Store("google.longrunning.Operations/WaitOperation", reflect.TypeOf((*google_longrunning_longrunningpb.WaitOperationRequest)(nil)).Elem())
	method2ResponseType.Store("google.longrunning.Operations/WaitOperation", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
