// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_sql_v1_cloud_sql_ssl_certspb "google.golang.org/genproto/googleapis/cloud/sql/v1"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.sql.v1.SqlSslCertsService", "sqladmin.googleapis.com")
	method2RequestType.Store("google.cloud.sql.v1.SqlSslCertsService/Delete", reflect.TypeOf((*google_cloud_sql_v1_cloud_sql_ssl_certspb.SqlSslCertsDeleteRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.sql.v1.SqlSslCertsService/Delete", reflect.TypeOf((*google_cloud_sql_v1_cloud_sql_ssl_certspb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.sql.v1.SqlSslCertsService/Get", reflect.TypeOf((*google_cloud_sql_v1_cloud_sql_ssl_certspb.SqlSslCertsGetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.sql.v1.SqlSslCertsService/Get", reflect.TypeOf((*google_cloud_sql_v1_cloud_sql_ssl_certspb.SslCert)(nil)).Elem())
	method2RequestType.Store("google.cloud.sql.v1.SqlSslCertsService/Insert", reflect.TypeOf((*google_cloud_sql_v1_cloud_sql_ssl_certspb.SqlSslCertsInsertRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.sql.v1.SqlSslCertsService/Insert", reflect.TypeOf((*google_cloud_sql_v1_cloud_sql_ssl_certspb.SslCertsInsertResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.sql.v1.SqlSslCertsService/List", reflect.TypeOf((*google_cloud_sql_v1_cloud_sql_ssl_certspb.SqlSslCertsListRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.sql.v1.SqlSslCertsService/List", reflect.TypeOf((*google_cloud_sql_v1_cloud_sql_ssl_certspb.SslCertsListResponse)(nil)).Elem())
}
