// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_bigquery_migration_v2_migrationpb "cloud.google.com/go/bigquery/migration/apiv2/migrationpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.bigquery.migration.v2.MigrationService", "bigquerymigration.googleapis.com")
	method2RequestType.Store("google.cloud.bigquery.migration.v2.MigrationService/CreateMigrationWorkflow", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.CreateMigrationWorkflowRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.migration.v2.MigrationService/CreateMigrationWorkflow", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.MigrationWorkflow)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.migration.v2.MigrationService/DeleteMigrationWorkflow", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.DeleteMigrationWorkflowRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.migration.v2.MigrationService/DeleteMigrationWorkflow", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.migration.v2.MigrationService/GetMigrationSubtask", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.GetMigrationSubtaskRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.migration.v2.MigrationService/GetMigrationSubtask", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.MigrationSubtask)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.migration.v2.MigrationService/GetMigrationWorkflow", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.GetMigrationWorkflowRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.migration.v2.MigrationService/GetMigrationWorkflow", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.MigrationWorkflow)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.migration.v2.MigrationService/ListMigrationSubtasks", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.ListMigrationSubtasksRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.migration.v2.MigrationService/ListMigrationSubtasks", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.ListMigrationSubtasksResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.migration.v2.MigrationService/ListMigrationWorkflows", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.ListMigrationWorkflowsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.migration.v2.MigrationService/ListMigrationWorkflows", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.ListMigrationWorkflowsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.migration.v2.MigrationService/StartMigrationWorkflow", reflect.TypeOf((*google_cloud_bigquery_migration_v2_migrationpb.StartMigrationWorkflowRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.migration.v2.MigrationService/StartMigrationWorkflow", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
}
