// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_discoveryengine_v1alpha_discoveryenginepb "cloud.google.com/go/discoveryengine/apiv1alpha/discoveryenginepb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.discoveryengine.v1alpha.CompletionService", "discoveryengine.googleapis.com")
	method2RequestType.Store("google.cloud.discoveryengine.v1alpha.CompletionService/CompleteQuery", reflect.TypeOf((*google_cloud_discoveryengine_v1alpha_discoveryenginepb.CompleteQueryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.discoveryengine.v1alpha.CompletionService/CompleteQuery", reflect.TypeOf((*google_cloud_discoveryengine_v1alpha_discoveryenginepb.CompleteQueryResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.discoveryengine.v1alpha.CompletionService/ImportSuggestionDenyListEntries", reflect.TypeOf((*google_cloud_discoveryengine_v1alpha_discoveryenginepb.ImportSuggestionDenyListEntriesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.discoveryengine.v1alpha.CompletionService/ImportSuggestionDenyListEntries", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.discoveryengine.v1alpha.CompletionService/PurgeSuggestionDenyListEntries", reflect.TypeOf((*google_cloud_discoveryengine_v1alpha_discoveryenginepb.PurgeSuggestionDenyListEntriesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.discoveryengine.v1alpha.CompletionService/PurgeSuggestionDenyListEntries", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
