// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_retail_v2beta_retailpb "cloud.google.com/go/retail/apiv2beta/retailpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.retail.v2beta.ModelService", "retail.googleapis.com")
	method2RequestType.Store("google.cloud.retail.v2beta.ModelService/CreateModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.CreateModelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.retail.v2beta.ModelService/CreateModel", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.retail.v2beta.ModelService/DeleteModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.DeleteModelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.retail.v2beta.ModelService/DeleteModel", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.retail.v2beta.ModelService/GetModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.GetModelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.retail.v2beta.ModelService/GetModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.Model)(nil)).Elem())
	method2RequestType.Store("google.cloud.retail.v2beta.ModelService/ListModels", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.ListModelsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.retail.v2beta.ModelService/ListModels", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.ListModelsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.retail.v2beta.ModelService/PauseModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.PauseModelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.retail.v2beta.ModelService/PauseModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.Model)(nil)).Elem())
	method2RequestType.Store("google.cloud.retail.v2beta.ModelService/ResumeModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.ResumeModelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.retail.v2beta.ModelService/ResumeModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.Model)(nil)).Elem())
	method2RequestType.Store("google.cloud.retail.v2beta.ModelService/TuneModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.TuneModelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.retail.v2beta.ModelService/TuneModel", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.retail.v2beta.ModelService/UpdateModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.UpdateModelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.retail.v2beta.ModelService/UpdateModel", reflect.TypeOf((*google_cloud_retail_v2beta_retailpb.Model)(nil)).Elem())
}
