// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_monitoring_metricsscope_v1_metricsscopepb "cloud.google.com/go/monitoring/metricsscope/apiv1/metricsscopepb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.monitoring.metricsscope.v1.MetricsScopes", "monitoring.googleapis.com")
	method2RequestType.Store("google.monitoring.metricsscope.v1.MetricsScopes/CreateMonitoredProject", reflect.TypeOf((*google_monitoring_metricsscope_v1_metricsscopepb.CreateMonitoredProjectRequest)(nil)).Elem())
	method2ResponseType.Store("google.monitoring.metricsscope.v1.MetricsScopes/CreateMonitoredProject", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.monitoring.metricsscope.v1.MetricsScopes/DeleteMonitoredProject", reflect.TypeOf((*google_monitoring_metricsscope_v1_metricsscopepb.DeleteMonitoredProjectRequest)(nil)).Elem())
	method2ResponseType.Store("google.monitoring.metricsscope.v1.MetricsScopes/DeleteMonitoredProject", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.monitoring.metricsscope.v1.MetricsScopes/GetMetricsScope", reflect.TypeOf((*google_monitoring_metricsscope_v1_metricsscopepb.GetMetricsScopeRequest)(nil)).Elem())
	method2ResponseType.Store("google.monitoring.metricsscope.v1.MetricsScopes/GetMetricsScope", reflect.TypeOf((*google_monitoring_metricsscope_v1_metricsscopepb.MetricsScope)(nil)).Elem())
	method2RequestType.Store("google.monitoring.metricsscope.v1.MetricsScopes/ListMetricsScopesByMonitoredProject", reflect.TypeOf((*google_monitoring_metricsscope_v1_metricsscopepb.ListMetricsScopesByMonitoredProjectRequest)(nil)).Elem())
	method2ResponseType.Store("google.monitoring.metricsscope.v1.MetricsScopes/ListMetricsScopesByMonitoredProject", reflect.TypeOf((*google_monitoring_metricsscope_v1_metricsscopepb.ListMetricsScopesByMonitoredProjectResponse)(nil)).Elem())
}
