// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_talent_v4_talentpb "cloud.google.com/go/talent/apiv4/talentpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.talent.v4.EventService", "jobs.googleapis.com")
	method2RequestType.Store("google.cloud.talent.v4.EventService/CreateClientEvent", reflect.TypeOf((*google_cloud_talent_v4_talentpb.CreateClientEventRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.talent.v4.EventService/CreateClientEvent", reflect.TypeOf((*google_cloud_talent_v4_talentpb.ClientEvent)(nil)).Elem())
}
