// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_commerce_consumer_procurement_v1_procurementpb "cloud.google.com/go/commerce/consumer/procurement/apiv1/procurementpb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService", "cloudcommerceconsumerprocurement.googleapis.com")
	method2RequestType.Store("google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService/GetOrder", reflect.TypeOf((*google_cloud_commerce_consumer_procurement_v1_procurementpb.GetOrderRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService/GetOrder", reflect.TypeOf((*google_cloud_commerce_consumer_procurement_v1_procurementpb.Order)(nil)).Elem())
	method2RequestType.Store("google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService/ListOrders", reflect.TypeOf((*google_cloud_commerce_consumer_procurement_v1_procurementpb.ListOrdersRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService/ListOrders", reflect.TypeOf((*google_cloud_commerce_consumer_procurement_v1_procurementpb.ListOrdersResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService/PlaceOrder", reflect.TypeOf((*google_cloud_commerce_consumer_procurement_v1_procurementpb.PlaceOrderRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService/PlaceOrder", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
