// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb "cloud.google.com/go/gdchardwaremanagement/apiv1alpha/gdchardwaremanagementpb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement", "gdchardwaremanagement.googleapis.com")
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateComment", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.CreateCommentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateComment", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateHardware", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.CreateHardwareRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateHardware", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateHardwareGroup", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.CreateHardwareGroupRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateHardwareGroup", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateOrder", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.CreateOrderRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateOrder", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateSite", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.CreateSiteRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateSite", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateZone", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.CreateZoneRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/CreateZone", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/DeleteHardware", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.DeleteHardwareRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/DeleteHardware", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/DeleteHardwareGroup", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.DeleteHardwareGroupRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/DeleteHardwareGroup", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/DeleteOrder", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.DeleteOrderRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/DeleteOrder", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/DeleteZone", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.DeleteZoneRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/DeleteZone", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetChangeLogEntry", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.GetChangeLogEntryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetChangeLogEntry", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ChangeLogEntry)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetComment", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.GetCommentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetComment", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.Comment)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetHardware", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.GetHardwareRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetHardware", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.Hardware)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetHardwareGroup", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.GetHardwareGroupRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetHardwareGroup", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.HardwareGroup)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetOrder", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.GetOrderRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetOrder", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.Order)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetSite", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.GetSiteRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetSite", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.Site)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetSku", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.GetSkuRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetSku", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.Sku)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetZone", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.GetZoneRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/GetZone", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.Zone)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListChangeLogEntries", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListChangeLogEntriesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListChangeLogEntries", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListChangeLogEntriesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListComments", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListCommentsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListComments", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListCommentsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListHardware", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListHardwareRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListHardware", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListHardwareResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListHardwareGroups", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListHardwareGroupsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListHardwareGroups", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListHardwareGroupsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListOrders", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListOrdersRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListOrders", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListOrdersResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListSites", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListSitesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListSites", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListSitesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListSkus", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListSkusRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListSkus", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListSkusResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListZones", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListZonesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/ListZones", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.ListZonesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/SignalZoneState", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.SignalZoneStateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/SignalZoneState", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/SubmitOrder", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.SubmitOrderRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/SubmitOrder", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/UpdateHardware", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.UpdateHardwareRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/UpdateHardware", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/UpdateHardwareGroup", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.UpdateHardwareGroupRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/UpdateHardwareGroup", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/UpdateOrder", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.UpdateOrderRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/UpdateOrder", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/UpdateSite", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.UpdateSiteRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/UpdateSite", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/UpdateZone", reflect.TypeOf((*google_cloud_gdchardwaremanagement_v1alpha_gdchardwaremanagementpb.UpdateZoneRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gdchardwaremanagement.v1alpha.GDCHardwareManagement/UpdateZone", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
