// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_streetview_publish_v1_streetview_publishpb "google.golang.org/genproto/googleapis/streetview/publish/v1"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.streetview.publish.v1.StreetViewPublishService", "streetviewpublish.googleapis.com")
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/BatchDeletePhotos", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.BatchDeletePhotosRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/BatchDeletePhotos", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.BatchDeletePhotosResponse)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/BatchGetPhotos", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.BatchGetPhotosRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/BatchGetPhotos", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.BatchGetPhotosResponse)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/BatchUpdatePhotos", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.BatchUpdatePhotosRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/BatchUpdatePhotos", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.BatchUpdatePhotosResponse)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/CreatePhoto", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.CreatePhotoRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/CreatePhoto", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.Photo)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/CreatePhotoSequence", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.CreatePhotoSequenceRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/CreatePhotoSequence", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/DeletePhoto", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.DeletePhotoRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/DeletePhoto", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/DeletePhotoSequence", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.DeletePhotoSequenceRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/DeletePhotoSequence", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/GetPhoto", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.GetPhotoRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/GetPhoto", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.Photo)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/GetPhotoSequence", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.GetPhotoSequenceRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/GetPhotoSequence", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/ListPhotoSequences", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.ListPhotoSequencesRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/ListPhotoSequences", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.ListPhotoSequencesResponse)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/ListPhotos", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.ListPhotosRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/ListPhotos", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.ListPhotosResponse)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/StartPhotoSequenceUpload", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/StartPhotoSequenceUpload", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.UploadRef)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/StartUpload", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/StartUpload", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.UploadRef)(nil)).Elem())
	method2RequestType.Store("google.streetview.publish.v1.StreetViewPublishService/UpdatePhoto", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.UpdatePhotoRequest)(nil)).Elem())
	method2ResponseType.Store("google.streetview.publish.v1.StreetViewPublishService/UpdatePhoto", reflect.TypeOf((*google_streetview_publish_v1_streetview_publishpb.Photo)(nil)).Elem())
}
