// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_iam_v1_iampb "cloud.google.com/go/iam/apiv1/iampb"
	google_cloud_secrets_v1beta1_secretspb "cloud.google.com/go/secrets/apiv1beta1/secretspb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.secrets.v1beta1.SecretManagerService", "secretmanager.googleapis.com")
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/AccessSecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.AccessSecretVersionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/AccessSecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.AccessSecretVersionResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/AddSecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.AddSecretVersionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/AddSecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.SecretVersion)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/CreateSecret", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.CreateSecretRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/CreateSecret", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.Secret)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/DeleteSecret", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.DeleteSecretRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/DeleteSecret", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/DestroySecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.DestroySecretVersionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/DestroySecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.SecretVersion)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/DisableSecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.DisableSecretVersionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/DisableSecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.SecretVersion)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/EnableSecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.EnableSecretVersionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/EnableSecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.SecretVersion)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.GetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/GetSecret", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.GetSecretRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/GetSecret", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.Secret)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/GetSecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.GetSecretVersionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/GetSecretVersion", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.SecretVersion)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/ListSecretVersions", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.ListSecretVersionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/ListSecretVersions", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.ListSecretVersionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/ListSecrets", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.ListSecretsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/ListSecrets", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.ListSecretsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.SetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.secrets.v1beta1.SecretManagerService/UpdateSecret", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.UpdateSecretRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.secrets.v1beta1.SecretManagerService/UpdateSecret", reflect.TypeOf((*google_cloud_secrets_v1beta1_secretspb.Secret)(nil)).Elem())
}
