// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_datacatalog_lineage_v1_lineagepb "cloud.google.com/go/datacatalog/lineage/apiv1/lineagepb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.datacatalog.lineage.v1.Lineage", "datalineage.googleapis.com")
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/BatchSearchLinkProcesses", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.BatchSearchLinkProcessesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/BatchSearchLinkProcesses", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.BatchSearchLinkProcessesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/CreateLineageEvent", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.CreateLineageEventRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/CreateLineageEvent", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.LineageEvent)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/CreateProcess", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.CreateProcessRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/CreateProcess", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.Process)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/CreateRun", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.CreateRunRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/CreateRun", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.Run)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/DeleteLineageEvent", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.DeleteLineageEventRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/DeleteLineageEvent", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/DeleteProcess", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.DeleteProcessRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/DeleteProcess", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/DeleteRun", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.DeleteRunRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/DeleteRun", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/GetLineageEvent", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.GetLineageEventRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/GetLineageEvent", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.LineageEvent)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/GetProcess", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.GetProcessRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/GetProcess", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.Process)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/GetRun", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.GetRunRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/GetRun", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.Run)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/ListLineageEvents", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.ListLineageEventsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/ListLineageEvents", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.ListLineageEventsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/ListProcesses", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.ListProcessesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/ListProcesses", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.ListProcessesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/ListRuns", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.ListRunsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/ListRuns", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.ListRunsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/ProcessOpenLineageRunEvent", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.ProcessOpenLineageRunEventRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/ProcessOpenLineageRunEvent", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.ProcessOpenLineageRunEventResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/SearchLinks", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.SearchLinksRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/SearchLinks", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.SearchLinksResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/UpdateProcess", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.UpdateProcessRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/UpdateProcess", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.Process)(nil)).Elem())
	method2RequestType.Store("google.cloud.datacatalog.lineage.v1.Lineage/UpdateRun", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.UpdateRunRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datacatalog.lineage.v1.Lineage/UpdateRun", reflect.TypeOf((*google_cloud_datacatalog_lineage_v1_lineagepb.Run)(nil)).Elem())
}
