// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_billing_v1_billingpb "cloud.google.com/go/billing/apiv1/billingpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.billing.v1.CloudCatalog", "cloudbilling.googleapis.com")
	method2RequestType.Store("google.cloud.billing.v1.CloudCatalog/ListServices", reflect.TypeOf((*google_cloud_billing_v1_billingpb.ListServicesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.billing.v1.CloudCatalog/ListServices", reflect.TypeOf((*google_cloud_billing_v1_billingpb.ListServicesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.billing.v1.CloudCatalog/ListSkus", reflect.TypeOf((*google_cloud_billing_v1_billingpb.ListSkusRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.billing.v1.CloudCatalog/ListSkus", reflect.TypeOf((*google_cloud_billing_v1_billingpb.ListSkusResponse)(nil)).Elem())
}
