// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_gkeconnect_gateway_v1beta1_gatewaypb "cloud.google.com/go/gkeconnect/gateway/apiv1beta1/gatewaypb"
	google_api_httpbodypb "google.golang.org/genproto/googleapis/api/httpbody"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService", "connectgateway.googleapis.com")
	method2RequestType.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService/DeleteResource", reflect.TypeOf((*google_api_httpbodypb.HttpBody)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService/DeleteResource", reflect.TypeOf((*google_api_httpbodypb.HttpBody)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService/GetResource", reflect.TypeOf((*google_api_httpbodypb.HttpBody)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService/GetResource", reflect.TypeOf((*google_api_httpbodypb.HttpBody)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService/PatchResource", reflect.TypeOf((*google_api_httpbodypb.HttpBody)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService/PatchResource", reflect.TypeOf((*google_api_httpbodypb.HttpBody)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService/PostResource", reflect.TypeOf((*google_api_httpbodypb.HttpBody)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService/PostResource", reflect.TypeOf((*google_api_httpbodypb.HttpBody)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService/PutResource", reflect.TypeOf((*google_api_httpbodypb.HttpBody)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkeconnect.gateway.v1beta1.GatewayService/PutResource", reflect.TypeOf((*google_api_httpbodypb.HttpBody)(nil)).Elem())
}
