// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_contentwarehouse_v1_document_servicepb "google.golang.org/genproto/googleapis/cloud/contentwarehouse/v1"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.contentwarehouse.v1.DocumentService", "contentwarehouse.googleapis.com")
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentService/CreateDocument", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.CreateDocumentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentService/CreateDocument", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.CreateDocumentResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentService/DeleteDocument", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.DeleteDocumentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentService/DeleteDocument", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentService/FetchAcl", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.FetchAclRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentService/FetchAcl", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.FetchAclResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentService/GetDocument", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.GetDocumentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentService/GetDocument", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.Document)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentService/LockDocument", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.LockDocumentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentService/LockDocument", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.Document)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentService/SearchDocuments", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.SearchDocumentsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentService/SearchDocuments", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.SearchDocumentsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentService/SetAcl", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.SetAclRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentService/SetAcl", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.SetAclResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.contentwarehouse.v1.DocumentService/UpdateDocument", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.UpdateDocumentRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.contentwarehouse.v1.DocumentService/UpdateDocument", reflect.TypeOf((*google_cloud_contentwarehouse_v1_document_servicepb.UpdateDocumentResponse)(nil)).Elem())
}
