// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_bigquery_analyticshub_v1_analyticshubpb "cloud.google.com/go/bigquery/analyticshub/apiv1/analyticshubpb"
	google_iam_v1_iampb "cloud.google.com/go/iam/apiv1/iampb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService", "analyticshub.googleapis.com")
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/CreateDataExchange", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.CreateDataExchangeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/CreateDataExchange", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.DataExchange)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/CreateListing", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.CreateListingRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/CreateListing", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.Listing)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/DeleteDataExchange", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.DeleteDataExchangeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/DeleteDataExchange", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/DeleteListing", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.DeleteListingRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/DeleteListing", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/DeleteSubscription", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.DeleteSubscriptionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/DeleteSubscription", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/GetDataExchange", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.GetDataExchangeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/GetDataExchange", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.DataExchange)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.GetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/GetListing", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.GetListingRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/GetListing", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.Listing)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/GetSubscription", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.GetSubscriptionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/GetSubscription", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.Subscription)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/ListDataExchanges", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.ListDataExchangesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/ListDataExchanges", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.ListDataExchangesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/ListListings", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.ListListingsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/ListListings", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.ListListingsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/ListOrgDataExchanges", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.ListOrgDataExchangesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/ListOrgDataExchanges", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.ListOrgDataExchangesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/ListSharedResourceSubscriptions", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.ListSharedResourceSubscriptionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/ListSharedResourceSubscriptions", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.ListSharedResourceSubscriptionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/ListSubscriptions", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.ListSubscriptionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/ListSubscriptions", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.ListSubscriptionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/RefreshSubscription", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.RefreshSubscriptionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/RefreshSubscription", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/RevokeSubscription", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.RevokeSubscriptionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/RevokeSubscription", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.RevokeSubscriptionResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.SetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/SubscribeDataExchange", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.SubscribeDataExchangeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/SubscribeDataExchange", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/SubscribeListing", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.SubscribeListingRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/SubscribeListing", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.SubscribeListingResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/UpdateDataExchange", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.UpdateDataExchangeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/UpdateDataExchange", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.DataExchange)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/UpdateListing", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.UpdateListingRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.analyticshub.v1.AnalyticsHubService/UpdateListing", reflect.TypeOf((*google_cloud_bigquery_analyticshub_v1_analyticshubpb.Listing)(nil)).Elem())
}
