// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_bigquery_datatransfer_v1_datatransferpb "cloud.google.com/go/bigquery/datatransfer/apiv1/datatransferpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService", "bigquerydatatransfer.googleapis.com")
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/CheckValidCreds", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.CheckValidCredsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/CheckValidCreds", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.CheckValidCredsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/CreateTransferConfig", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.CreateTransferConfigRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/CreateTransferConfig", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.TransferConfig)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/DeleteTransferConfig", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.DeleteTransferConfigRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/DeleteTransferConfig", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/DeleteTransferRun", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.DeleteTransferRunRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/DeleteTransferRun", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/EnrollDataSources", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.EnrollDataSourcesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/EnrollDataSources", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/GetDataSource", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.GetDataSourceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/GetDataSource", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.DataSource)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/GetTransferConfig", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.GetTransferConfigRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/GetTransferConfig", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.TransferConfig)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/GetTransferRun", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.GetTransferRunRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/GetTransferRun", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.TransferRun)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/ListDataSources", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.ListDataSourcesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/ListDataSources", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.ListDataSourcesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/ListTransferConfigs", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.ListTransferConfigsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/ListTransferConfigs", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.ListTransferConfigsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/ListTransferLogs", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.ListTransferLogsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/ListTransferLogs", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.ListTransferLogsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/ListTransferRuns", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.ListTransferRunsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/ListTransferRuns", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.ListTransferRunsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/ScheduleTransferRuns", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.ScheduleTransferRunsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/ScheduleTransferRuns", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.ScheduleTransferRunsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/StartManualTransferRuns", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.StartManualTransferRunsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/StartManualTransferRuns", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.StartManualTransferRunsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/UnenrollDataSources", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.UnenrollDataSourcesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/UnenrollDataSources", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/UpdateTransferConfig", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.UpdateTransferConfigRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.datatransfer.v1.DataTransferService/UpdateTransferConfig", reflect.TypeOf((*google_cloud_bigquery_datatransfer_v1_datatransferpb.TransferConfig)(nil)).Elem())
}
