// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_datalabeling_v1beta1_datalabelingpb "cloud.google.com/go/datalabeling/apiv1beta1/datalabelingpb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.datalabeling.v1beta1.DataLabelingService", "datalabeling.googleapis.com")
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/CreateAnnotationSpecSet", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.CreateAnnotationSpecSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/CreateAnnotationSpecSet", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.AnnotationSpecSet)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/CreateDataset", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.CreateDatasetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/CreateDataset", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.Dataset)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/CreateEvaluationJob", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.CreateEvaluationJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/CreateEvaluationJob", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.EvaluationJob)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/CreateInstruction", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.CreateInstructionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/CreateInstruction", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/DeleteAnnotatedDataset", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.DeleteAnnotatedDatasetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/DeleteAnnotatedDataset", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/DeleteAnnotationSpecSet", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.DeleteAnnotationSpecSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/DeleteAnnotationSpecSet", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/DeleteDataset", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.DeleteDatasetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/DeleteDataset", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/DeleteEvaluationJob", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.DeleteEvaluationJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/DeleteEvaluationJob", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/DeleteInstruction", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.DeleteInstructionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/DeleteInstruction", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ExportData", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ExportDataRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ExportData", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetAnnotatedDataset", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.GetAnnotatedDatasetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetAnnotatedDataset", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.AnnotatedDataset)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetAnnotationSpecSet", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.GetAnnotationSpecSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetAnnotationSpecSet", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.AnnotationSpecSet)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetDataItem", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.GetDataItemRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetDataItem", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.DataItem)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetDataset", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.GetDatasetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetDataset", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.Dataset)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetEvaluation", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.GetEvaluationRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetEvaluation", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.Evaluation)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetEvaluationJob", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.GetEvaluationJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetEvaluationJob", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.EvaluationJob)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetExample", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.GetExampleRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetExample", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.Example)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetInstruction", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.GetInstructionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/GetInstruction", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.Instruction)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ImportData", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ImportDataRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ImportData", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/LabelImage", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.LabelImageRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/LabelImage", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/LabelText", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.LabelTextRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/LabelText", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/LabelVideo", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.LabelVideoRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/LabelVideo", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListAnnotatedDatasets", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListAnnotatedDatasetsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListAnnotatedDatasets", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListAnnotatedDatasetsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListAnnotationSpecSets", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListAnnotationSpecSetsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListAnnotationSpecSets", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListAnnotationSpecSetsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListDataItems", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListDataItemsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListDataItems", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListDataItemsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListDatasets", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListDatasetsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListDatasets", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListDatasetsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListEvaluationJobs", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListEvaluationJobsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListEvaluationJobs", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListEvaluationJobsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListExamples", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListExamplesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListExamples", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListExamplesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListInstructions", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListInstructionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ListInstructions", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ListInstructionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/PauseEvaluationJob", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.PauseEvaluationJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/PauseEvaluationJob", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ResumeEvaluationJob", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.ResumeEvaluationJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/ResumeEvaluationJob", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/SearchEvaluations", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.SearchEvaluationsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/SearchEvaluations", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.SearchEvaluationsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/SearchExampleComparisons", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.SearchExampleComparisonsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/SearchExampleComparisons", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.SearchExampleComparisonsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/UpdateEvaluationJob", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.UpdateEvaluationJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.datalabeling.v1beta1.DataLabelingService/UpdateEvaluationJob", reflect.TypeOf((*google_cloud_datalabeling_v1beta1_datalabelingpb.EvaluationJob)(nil)).Elem())
}
