// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb "cloud.google.com/go/privilegedaccessmanager/apiv1/privilegedaccessmanagerpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager", "privilegedaccessmanager.googleapis.com")
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/ApproveGrant", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.ApproveGrantRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/ApproveGrant", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.Grant)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/CheckOnboardingStatus", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.CheckOnboardingStatusRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/CheckOnboardingStatus", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.CheckOnboardingStatusResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/CreateEntitlement", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.CreateEntitlementRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/CreateEntitlement", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/CreateGrant", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.CreateGrantRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/CreateGrant", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.Grant)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/DeleteEntitlement", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.DeleteEntitlementRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/DeleteEntitlement", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/DenyGrant", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.DenyGrantRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/DenyGrant", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.Grant)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/GetEntitlement", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.GetEntitlementRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/GetEntitlement", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.Entitlement)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/GetGrant", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.GetGrantRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/GetGrant", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.Grant)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/ListEntitlements", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.ListEntitlementsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/ListEntitlements", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.ListEntitlementsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/ListGrants", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.ListGrantsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/ListGrants", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.ListGrantsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/RevokeGrant", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.RevokeGrantRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/RevokeGrant", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/SearchEntitlements", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.SearchEntitlementsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/SearchEntitlements", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.SearchEntitlementsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/SearchGrants", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.SearchGrantsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/SearchGrants", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.SearchGrantsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/UpdateEntitlement", reflect.TypeOf((*google_cloud_privilegedaccessmanager_v1_privilegedaccessmanagerpb.UpdateEntitlementRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.privilegedaccessmanager.v1.PrivilegedAccessManager/UpdateEntitlement", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
