// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_shopping_css_v1_csspb "cloud.google.com/go/shopping/css/apiv1/csspb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.shopping.css.v1.CssProductsService", "css.googleapis.com")
	method2RequestType.Store("google.shopping.css.v1.CssProductsService/GetCssProduct", reflect.TypeOf((*google_shopping_css_v1_csspb.GetCssProductRequest)(nil)).Elem())
	method2ResponseType.Store("google.shopping.css.v1.CssProductsService/GetCssProduct", reflect.TypeOf((*google_shopping_css_v1_csspb.CssProduct)(nil)).Elem())
	method2RequestType.Store("google.shopping.css.v1.CssProductsService/ListCssProducts", reflect.TypeOf((*google_shopping_css_v1_csspb.ListCssProductsRequest)(nil)).Elem())
	method2ResponseType.Store("google.shopping.css.v1.CssProductsService/ListCssProducts", reflect.TypeOf((*google_shopping_css_v1_csspb.ListCssProductsResponse)(nil)).Elem())
}
