// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_eventarc_v1_eventarcpb "cloud.google.com/go/eventarc/apiv1/eventarcpb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.eventarc.v1.Eventarc", "eventarc.googleapis.com")
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/CreateChannel", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.CreateChannelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/CreateChannel", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/CreateChannelConnection", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.CreateChannelConnectionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/CreateChannelConnection", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/CreateTrigger", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.CreateTriggerRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/CreateTrigger", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/DeleteChannel", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.DeleteChannelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/DeleteChannel", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/DeleteChannelConnection", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.DeleteChannelConnectionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/DeleteChannelConnection", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/DeleteTrigger", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.DeleteTriggerRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/DeleteTrigger", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/GetChannel", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.GetChannelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/GetChannel", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.Channel)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/GetChannelConnection", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.GetChannelConnectionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/GetChannelConnection", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.ChannelConnection)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/GetGoogleChannelConfig", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.GetGoogleChannelConfigRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/GetGoogleChannelConfig", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.GoogleChannelConfig)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/GetProvider", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.GetProviderRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/GetProvider", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.Provider)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/GetTrigger", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.GetTriggerRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/GetTrigger", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.Trigger)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/ListChannelConnections", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.ListChannelConnectionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/ListChannelConnections", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.ListChannelConnectionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/ListChannels", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.ListChannelsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/ListChannels", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.ListChannelsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/ListProviders", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.ListProvidersRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/ListProviders", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.ListProvidersResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/ListTriggers", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.ListTriggersRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/ListTriggers", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.ListTriggersResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/UpdateChannel", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.UpdateChannelRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/UpdateChannel", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/UpdateGoogleChannelConfig", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.UpdateGoogleChannelConfigRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/UpdateGoogleChannelConfig", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.GoogleChannelConfig)(nil)).Elem())
	method2RequestType.Store("google.cloud.eventarc.v1.Eventarc/UpdateTrigger", reflect.TypeOf((*google_cloud_eventarc_v1_eventarcpb.UpdateTriggerRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.eventarc.v1.Eventarc/UpdateTrigger", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
