// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_websecurityscanner_v1alpha_web_security_scannerpb "google.golang.org/genproto/googleapis/cloud/websecurityscanner/v1alpha"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner", "websecurityscanner.googleapis.com")
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/CreateScanConfig", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.CreateScanConfigRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/CreateScanConfig", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ScanConfig)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/DeleteScanConfig", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.DeleteScanConfigRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/DeleteScanConfig", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/GetFinding", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.GetFindingRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/GetFinding", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.Finding)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/GetScanConfig", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.GetScanConfigRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/GetScanConfig", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ScanConfig)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/GetScanRun", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.GetScanRunRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/GetScanRun", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ScanRun)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListCrawledUrls", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ListCrawledUrlsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListCrawledUrls", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ListCrawledUrlsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListFindingTypeStats", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ListFindingTypeStatsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListFindingTypeStats", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ListFindingTypeStatsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListFindings", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ListFindingsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListFindings", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ListFindingsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListScanConfigs", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ListScanConfigsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListScanConfigs", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ListScanConfigsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListScanRuns", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ListScanRunsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListScanRuns", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ListScanRunsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/StartScanRun", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.StartScanRunRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/StartScanRun", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ScanRun)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/StopScanRun", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.StopScanRunRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/StopScanRun", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ScanRun)(nil)).Elem())
	method2RequestType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/UpdateScanConfig", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.UpdateScanConfigRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/UpdateScanConfig", reflect.TypeOf((*google_cloud_websecurityscanner_v1alpha_web_security_scannerpb.ScanConfig)(nil)).Elem())
}
