// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_maps_regionlookup_v1alpha_region_lookup_servicepb "google.golang.org/genproto/googleapis/maps/regionlookup/v1alpha"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.maps.regionlookup.v1alpha.RegionLookup", "regionlookup.googleapis.com")
	method2RequestType.Store("google.maps.regionlookup.v1alpha.RegionLookup/LookupRegion", reflect.TypeOf((*google_maps_regionlookup_v1alpha_region_lookup_servicepb.LookupRegionRequest)(nil)).Elem())
	method2ResponseType.Store("google.maps.regionlookup.v1alpha.RegionLookup/LookupRegion", reflect.TypeOf((*google_maps_regionlookup_v1alpha_region_lookup_servicepb.LookupRegionResponse)(nil)).Elem())
	method2RequestType.Store("google.maps.regionlookup.v1alpha.RegionLookup/SearchRegion", reflect.TypeOf((*google_maps_regionlookup_v1alpha_region_lookup_servicepb.SearchRegionRequest)(nil)).Elem())
	method2ResponseType.Store("google.maps.regionlookup.v1alpha.RegionLookup/SearchRegion", reflect.TypeOf((*google_maps_regionlookup_v1alpha_region_lookup_servicepb.SearchRegionResponse)(nil)).Elem())
}
