// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_scheduler_v1beta1_schedulerpb "cloud.google.com/go/scheduler/apiv1beta1/schedulerpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.scheduler.v1beta1.CloudScheduler", "cloudscheduler.googleapis.com")
	method2RequestType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/CreateJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.CreateJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/CreateJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.Job)(nil)).Elem())
	method2RequestType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/DeleteJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.DeleteJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/DeleteJob", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/GetJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.GetJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/GetJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.Job)(nil)).Elem())
	method2RequestType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/ListJobs", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.ListJobsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/ListJobs", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.ListJobsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/PauseJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.PauseJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/PauseJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.Job)(nil)).Elem())
	method2RequestType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/ResumeJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.ResumeJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/ResumeJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.Job)(nil)).Elem())
	method2RequestType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/RunJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.RunJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/RunJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.Job)(nil)).Elem())
	method2RequestType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/UpdateJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.UpdateJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.scheduler.v1beta1.CloudScheduler/UpdateJob", reflect.TypeOf((*google_cloud_scheduler_v1beta1_schedulerpb.Job)(nil)).Elem())
}
