// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_apps_meet_v2_meetpb "cloud.google.com/go/apps/meet/apiv2/meetpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.apps.meet.v2.ConferenceRecordsService", "meet.googleapis.com")
	service2Host.Store("google.apps.meet.v2.SpacesService", "meet.googleapis.com")
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/GetConferenceRecord", reflect.TypeOf((*google_apps_meet_v2_meetpb.GetConferenceRecordRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/GetConferenceRecord", reflect.TypeOf((*google_apps_meet_v2_meetpb.ConferenceRecord)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/GetParticipant", reflect.TypeOf((*google_apps_meet_v2_meetpb.GetParticipantRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/GetParticipant", reflect.TypeOf((*google_apps_meet_v2_meetpb.Participant)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/GetParticipantSession", reflect.TypeOf((*google_apps_meet_v2_meetpb.GetParticipantSessionRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/GetParticipantSession", reflect.TypeOf((*google_apps_meet_v2_meetpb.ParticipantSession)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/GetRecording", reflect.TypeOf((*google_apps_meet_v2_meetpb.GetRecordingRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/GetRecording", reflect.TypeOf((*google_apps_meet_v2_meetpb.Recording)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/GetTranscript", reflect.TypeOf((*google_apps_meet_v2_meetpb.GetTranscriptRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/GetTranscript", reflect.TypeOf((*google_apps_meet_v2_meetpb.Transcript)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/GetTranscriptEntry", reflect.TypeOf((*google_apps_meet_v2_meetpb.GetTranscriptEntryRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/GetTranscriptEntry", reflect.TypeOf((*google_apps_meet_v2_meetpb.TranscriptEntry)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/ListConferenceRecords", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListConferenceRecordsRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/ListConferenceRecords", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListConferenceRecordsResponse)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/ListParticipantSessions", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListParticipantSessionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/ListParticipantSessions", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListParticipantSessionsResponse)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/ListParticipants", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListParticipantsRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/ListParticipants", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListParticipantsResponse)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/ListRecordings", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListRecordingsRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/ListRecordings", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListRecordingsResponse)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/ListTranscriptEntries", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListTranscriptEntriesRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/ListTranscriptEntries", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListTranscriptEntriesResponse)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.ConferenceRecordsService/ListTranscripts", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListTranscriptsRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.ConferenceRecordsService/ListTranscripts", reflect.TypeOf((*google_apps_meet_v2_meetpb.ListTranscriptsResponse)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.SpacesService/CreateSpace", reflect.TypeOf((*google_apps_meet_v2_meetpb.CreateSpaceRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.SpacesService/CreateSpace", reflect.TypeOf((*google_apps_meet_v2_meetpb.Space)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.SpacesService/EndActiveConference", reflect.TypeOf((*google_apps_meet_v2_meetpb.EndActiveConferenceRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.SpacesService/EndActiveConference", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.SpacesService/GetSpace", reflect.TypeOf((*google_apps_meet_v2_meetpb.GetSpaceRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.SpacesService/GetSpace", reflect.TypeOf((*google_apps_meet_v2_meetpb.Space)(nil)).Elem())
	method2RequestType.Store("google.apps.meet.v2.SpacesService/UpdateSpace", reflect.TypeOf((*google_apps_meet_v2_meetpb.UpdateSpaceRequest)(nil)).Elem())
	method2ResponseType.Store("google.apps.meet.v2.SpacesService/UpdateSpace", reflect.TypeOf((*google_apps_meet_v2_meetpb.Space)(nil)).Elem())
}
