// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_alloydb_v1_alloydbpb "cloud.google.com/go/alloydb/apiv1/alloydbpb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.alloydb.v1.AlloyDBAdmin", "alloydb.googleapis.com")
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/BatchCreateInstances", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.BatchCreateInstancesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/BatchCreateInstances", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateBackup", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.CreateBackupRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateBackup", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateCluster", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.CreateClusterRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateCluster", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateInstance", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.CreateInstanceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateInstance", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateSecondaryCluster", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.CreateSecondaryClusterRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateSecondaryCluster", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateSecondaryInstance", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.CreateSecondaryInstanceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateSecondaryInstance", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateUser", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.CreateUserRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/CreateUser", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.User)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/DeleteBackup", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.DeleteBackupRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/DeleteBackup", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/DeleteCluster", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.DeleteClusterRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/DeleteCluster", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/DeleteInstance", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.DeleteInstanceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/DeleteInstance", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/DeleteUser", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.DeleteUserRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/DeleteUser", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/FailoverInstance", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.FailoverInstanceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/FailoverInstance", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GenerateClientCertificate", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.GenerateClientCertificateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GenerateClientCertificate", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.GenerateClientCertificateResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GetBackup", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.GetBackupRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GetBackup", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.Backup)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GetCluster", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.GetClusterRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GetCluster", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.Cluster)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GetConnectionInfo", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.GetConnectionInfoRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GetConnectionInfo", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ConnectionInfo)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GetInstance", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.GetInstanceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GetInstance", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.Instance)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GetUser", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.GetUserRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/GetUser", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.User)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/InjectFault", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.InjectFaultRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/InjectFault", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/ListBackups", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ListBackupsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/ListBackups", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ListBackupsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/ListClusters", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ListClustersRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/ListClusters", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ListClustersResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/ListInstances", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ListInstancesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/ListInstances", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ListInstancesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/ListSupportedDatabaseFlags", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ListSupportedDatabaseFlagsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/ListSupportedDatabaseFlags", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ListSupportedDatabaseFlagsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/ListUsers", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ListUsersRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/ListUsers", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.ListUsersResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/PromoteCluster", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.PromoteClusterRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/PromoteCluster", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/RestartInstance", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.RestartInstanceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/RestartInstance", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/RestoreCluster", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.RestoreClusterRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/RestoreCluster", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/UpdateBackup", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.UpdateBackupRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/UpdateBackup", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/UpdateCluster", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.UpdateClusterRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/UpdateCluster", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/UpdateInstance", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.UpdateInstanceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/UpdateInstance", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/UpdateUser", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.UpdateUserRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.alloydb.v1.AlloyDBAdmin/UpdateUser", reflect.TypeOf((*google_cloud_alloydb_v1_alloydbpb.User)(nil)).Elem())
}
