// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_devtools_build_v1_publish_build_eventpb "google.golang.org/genproto/googleapis/devtools/build/v1"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.devtools.build.v1.PublishBuildEvent", "buildeventservice.googleapis.com")
	method2RequestType.Store("google.devtools.build.v1.PublishBuildEvent/PublishBuildToolEventStream", reflect.TypeOf((*google_devtools_build_v1_publish_build_eventpb.PublishBuildToolEventStreamRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.build.v1.PublishBuildEvent/PublishBuildToolEventStream", reflect.TypeOf((*google_devtools_build_v1_publish_build_eventpb.PublishBuildToolEventStreamResponse)(nil)).Elem())
	method2RequestType.Store("google.devtools.build.v1.PublishBuildEvent/PublishLifecycleEvent", reflect.TypeOf((*google_devtools_build_v1_publish_build_eventpb.PublishLifecycleEventRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.build.v1.PublishBuildEvent/PublishLifecycleEvent", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
}
