// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_retail_v2_retailpb "cloud.google.com/go/retail/apiv2/retailpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.retail.v2.CompletionService", "retail.googleapis.com")
	method2RequestType.Store("google.cloud.retail.v2.CompletionService/CompleteQuery", reflect.TypeOf((*google_cloud_retail_v2_retailpb.CompleteQueryRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.retail.v2.CompletionService/CompleteQuery", reflect.TypeOf((*google_cloud_retail_v2_retailpb.CompleteQueryResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.retail.v2.CompletionService/ImportCompletionData", reflect.TypeOf((*google_cloud_retail_v2_retailpb.ImportCompletionDataRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.retail.v2.CompletionService/ImportCompletionData", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
