// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_apigeeconnect_v1_apigeeconnectpb "cloud.google.com/go/apigeeconnect/apiv1/apigeeconnectpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.apigeeconnect.v1.ConnectionService", "apigeeconnect.googleapis.com")
	method2RequestType.Store("google.cloud.apigeeconnect.v1.ConnectionService/ListConnections", reflect.TypeOf((*google_cloud_apigeeconnect_v1_apigeeconnectpb.ListConnectionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.apigeeconnect.v1.ConnectionService/ListConnections", reflect.TypeOf((*google_cloud_apigeeconnect_v1_apigeeconnectpb.ListConnectionsResponse)(nil)).Elem())
}
