// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_iam_v1_iampb "cloud.google.com/go/iam/apiv1/iampb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_run_v2_runpb "cloud.google.com/go/run/apiv2/runpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.run.v2.Services", "run.googleapis.com")
	method2RequestType.Store("google.cloud.run.v2.Services/CreateService", reflect.TypeOf((*google_cloud_run_v2_runpb.CreateServiceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.run.v2.Services/CreateService", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.run.v2.Services/DeleteService", reflect.TypeOf((*google_cloud_run_v2_runpb.DeleteServiceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.run.v2.Services/DeleteService", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.run.v2.Services/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.GetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.run.v2.Services/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.run.v2.Services/GetService", reflect.TypeOf((*google_cloud_run_v2_runpb.GetServiceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.run.v2.Services/GetService", reflect.TypeOf((*google_cloud_run_v2_runpb.Service)(nil)).Elem())
	method2RequestType.Store("google.cloud.run.v2.Services/ListServices", reflect.TypeOf((*google_cloud_run_v2_runpb.ListServicesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.run.v2.Services/ListServices", reflect.TypeOf((*google_cloud_run_v2_runpb.ListServicesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.run.v2.Services/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.SetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.run.v2.Services/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.run.v2.Services/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.run.v2.Services/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.run.v2.Services/UpdateService", reflect.TypeOf((*google_cloud_run_v2_runpb.UpdateServiceRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.run.v2.Services/UpdateService", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
