// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_bigquery_connection_v1beta1_connectionpb "cloud.google.com/go/bigquery/connection/apiv1beta1/connectionpb"
	google_iam_v1_iampb "cloud.google.com/go/iam/apiv1/iampb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService", "bigqueryconnection.googleapis.com")
	method2RequestType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/CreateConnection", reflect.TypeOf((*google_cloud_bigquery_connection_v1beta1_connectionpb.CreateConnectionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/CreateConnection", reflect.TypeOf((*google_cloud_bigquery_connection_v1beta1_connectionpb.Connection)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/DeleteConnection", reflect.TypeOf((*google_cloud_bigquery_connection_v1beta1_connectionpb.DeleteConnectionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/DeleteConnection", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/GetConnection", reflect.TypeOf((*google_cloud_bigquery_connection_v1beta1_connectionpb.GetConnectionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/GetConnection", reflect.TypeOf((*google_cloud_bigquery_connection_v1beta1_connectionpb.Connection)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.GetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/GetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/ListConnections", reflect.TypeOf((*google_cloud_bigquery_connection_v1beta1_connectionpb.ListConnectionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/ListConnections", reflect.TypeOf((*google_cloud_bigquery_connection_v1beta1_connectionpb.ListConnectionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.SetIamPolicyRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/SetIamPolicy", reflect.TypeOf((*google_iam_v1_iampb.Policy)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/TestIamPermissions", reflect.TypeOf((*google_iam_v1_iampb.TestIamPermissionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/UpdateConnection", reflect.TypeOf((*google_cloud_bigquery_connection_v1beta1_connectionpb.UpdateConnectionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/UpdateConnection", reflect.TypeOf((*google_cloud_bigquery_connection_v1beta1_connectionpb.Connection)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/UpdateConnectionCredential", reflect.TypeOf((*google_cloud_bigquery_connection_v1beta1_connectionpb.UpdateConnectionCredentialRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.connection.v1beta1.ConnectionService/UpdateConnectionCredential", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
}
