// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_webrisk_v1beta1_webriskpb "cloud.google.com/go/webrisk/apiv1beta1/webriskpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.webrisk.v1beta1.WebRiskServiceV1Beta1", "webrisk.googleapis.com")
	method2RequestType.Store("google.cloud.webrisk.v1beta1.WebRiskServiceV1Beta1/ComputeThreatListDiff", reflect.TypeOf((*google_cloud_webrisk_v1beta1_webriskpb.ComputeThreatListDiffRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.webrisk.v1beta1.WebRiskServiceV1Beta1/ComputeThreatListDiff", reflect.TypeOf((*google_cloud_webrisk_v1beta1_webriskpb.ComputeThreatListDiffResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.webrisk.v1beta1.WebRiskServiceV1Beta1/SearchHashes", reflect.TypeOf((*google_cloud_webrisk_v1beta1_webriskpb.SearchHashesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.webrisk.v1beta1.WebRiskServiceV1Beta1/SearchHashes", reflect.TypeOf((*google_cloud_webrisk_v1beta1_webriskpb.SearchHashesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.webrisk.v1beta1.WebRiskServiceV1Beta1/SearchUris", reflect.TypeOf((*google_cloud_webrisk_v1beta1_webriskpb.SearchUrisRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.webrisk.v1beta1.WebRiskServiceV1Beta1/SearchUris", reflect.TypeOf((*google_cloud_webrisk_v1beta1_webriskpb.SearchUrisResponse)(nil)).Elem())
}
