// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_speech_v1p1beta1_speechpb "cloud.google.com/go/speech/apiv1p1beta1/speechpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.speech.v1p1beta1.Adaptation", "speech.googleapis.com")
	method2RequestType.Store("google.cloud.speech.v1p1beta1.Adaptation/CreateCustomClass", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.CreateCustomClassRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.speech.v1p1beta1.Adaptation/CreateCustomClass", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.CustomClass)(nil)).Elem())
	method2RequestType.Store("google.cloud.speech.v1p1beta1.Adaptation/CreatePhraseSet", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.CreatePhraseSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.speech.v1p1beta1.Adaptation/CreatePhraseSet", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.PhraseSet)(nil)).Elem())
	method2RequestType.Store("google.cloud.speech.v1p1beta1.Adaptation/DeleteCustomClass", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.DeleteCustomClassRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.speech.v1p1beta1.Adaptation/DeleteCustomClass", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.speech.v1p1beta1.Adaptation/DeletePhraseSet", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.DeletePhraseSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.speech.v1p1beta1.Adaptation/DeletePhraseSet", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.speech.v1p1beta1.Adaptation/GetCustomClass", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.GetCustomClassRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.speech.v1p1beta1.Adaptation/GetCustomClass", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.CustomClass)(nil)).Elem())
	method2RequestType.Store("google.cloud.speech.v1p1beta1.Adaptation/GetPhraseSet", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.GetPhraseSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.speech.v1p1beta1.Adaptation/GetPhraseSet", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.PhraseSet)(nil)).Elem())
	method2RequestType.Store("google.cloud.speech.v1p1beta1.Adaptation/ListCustomClasses", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.ListCustomClassesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.speech.v1p1beta1.Adaptation/ListCustomClasses", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.ListCustomClassesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.speech.v1p1beta1.Adaptation/ListPhraseSet", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.ListPhraseSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.speech.v1p1beta1.Adaptation/ListPhraseSet", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.ListPhraseSetResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.speech.v1p1beta1.Adaptation/UpdateCustomClass", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.UpdateCustomClassRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.speech.v1p1beta1.Adaptation/UpdateCustomClass", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.CustomClass)(nil)).Elem())
	method2RequestType.Store("google.cloud.speech.v1p1beta1.Adaptation/UpdatePhraseSet", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.UpdatePhraseSetRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.speech.v1p1beta1.Adaptation/UpdatePhraseSet", reflect.TypeOf((*google_cloud_speech_v1p1beta1_speechpb.PhraseSet)(nil)).Elem())
}
