// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_cloudcontrolspartner_v1_cloudcontrolspartnerpb "cloud.google.com/go/cloudcontrolspartner/apiv1/cloudcontrolspartnerpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.cloudcontrolspartner.v1.CloudControlsPartnerMonitoring", "cloudcontrolspartner.googleapis.com")
	method2RequestType.Store("google.cloud.cloudcontrolspartner.v1.CloudControlsPartnerMonitoring/GetViolation", reflect.TypeOf((*google_cloud_cloudcontrolspartner_v1_cloudcontrolspartnerpb.GetViolationRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.cloudcontrolspartner.v1.CloudControlsPartnerMonitoring/GetViolation", reflect.TypeOf((*google_cloud_cloudcontrolspartner_v1_cloudcontrolspartnerpb.Violation)(nil)).Elem())
	method2RequestType.Store("google.cloud.cloudcontrolspartner.v1.CloudControlsPartnerMonitoring/ListViolations", reflect.TypeOf((*google_cloud_cloudcontrolspartner_v1_cloudcontrolspartnerpb.ListViolationsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.cloudcontrolspartner.v1.CloudControlsPartnerMonitoring/ListViolations", reflect.TypeOf((*google_cloud_cloudcontrolspartner_v1_cloudcontrolspartnerpb.ListViolationsResponse)(nil)).Elem())
}
