// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_networkconnectivity_v1_networkconnectivitypb "cloud.google.com/go/networkconnectivity/apiv1/networkconnectivitypb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.networkconnectivity.v1.HubService", "networkconnectivity.googleapis.com")
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/AcceptHubSpoke", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.AcceptHubSpokeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/AcceptHubSpoke", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/CreateHub", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.CreateHubRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/CreateHub", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/CreateSpoke", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.CreateSpokeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/CreateSpoke", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/DeleteHub", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.DeleteHubRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/DeleteHub", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/DeleteSpoke", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.DeleteSpokeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/DeleteSpoke", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/GetGroup", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.GetGroupRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/GetGroup", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.Group)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/GetHub", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.GetHubRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/GetHub", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.Hub)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/GetRoute", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.GetRouteRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/GetRoute", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.Route)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/GetRouteTable", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.GetRouteTableRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/GetRouteTable", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.RouteTable)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/GetSpoke", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.GetSpokeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/GetSpoke", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.Spoke)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/ListGroups", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListGroupsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/ListGroups", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListGroupsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/ListHubSpokes", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListHubSpokesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/ListHubSpokes", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListHubSpokesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/ListHubs", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListHubsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/ListHubs", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListHubsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/ListRouteTables", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListRouteTablesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/ListRouteTables", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListRouteTablesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/ListRoutes", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListRoutesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/ListRoutes", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListRoutesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/ListSpokes", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListSpokesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/ListSpokes", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.ListSpokesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/RejectHubSpoke", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.RejectHubSpokeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/RejectHubSpoke", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/UpdateHub", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.UpdateHubRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/UpdateHub", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.networkconnectivity.v1.HubService/UpdateSpoke", reflect.TypeOf((*google_cloud_networkconnectivity_v1_networkconnectivitypb.UpdateSpokeRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.networkconnectivity.v1.HubService/UpdateSpoke", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
