// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_devtools_cloudprofiler_v2_profilerpb "google.golang.org/genproto/googleapis/devtools/cloudprofiler/v2"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.devtools.cloudprofiler.v2.ExportService", "cloudprofiler.googleapis.com")
	service2Host.Store("google.devtools.cloudprofiler.v2.ProfilerService", "cloudprofiler.googleapis.com")
	method2RequestType.Store("google.devtools.cloudprofiler.v2.ExportService/ListProfiles", reflect.TypeOf((*google_devtools_cloudprofiler_v2_profilerpb.ListProfilesRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.cloudprofiler.v2.ExportService/ListProfiles", reflect.TypeOf((*google_devtools_cloudprofiler_v2_profilerpb.ListProfilesResponse)(nil)).Elem())
	method2RequestType.Store("google.devtools.cloudprofiler.v2.ProfilerService/CreateOfflineProfile", reflect.TypeOf((*google_devtools_cloudprofiler_v2_profilerpb.CreateOfflineProfileRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.cloudprofiler.v2.ProfilerService/CreateOfflineProfile", reflect.TypeOf((*google_devtools_cloudprofiler_v2_profilerpb.Profile)(nil)).Elem())
	method2RequestType.Store("google.devtools.cloudprofiler.v2.ProfilerService/CreateProfile", reflect.TypeOf((*google_devtools_cloudprofiler_v2_profilerpb.CreateProfileRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.cloudprofiler.v2.ProfilerService/CreateProfile", reflect.TypeOf((*google_devtools_cloudprofiler_v2_profilerpb.Profile)(nil)).Elem())
	method2RequestType.Store("google.devtools.cloudprofiler.v2.ProfilerService/UpdateProfile", reflect.TypeOf((*google_devtools_cloudprofiler_v2_profilerpb.UpdateProfileRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.cloudprofiler.v2.ProfilerService/UpdateProfile", reflect.TypeOf((*google_devtools_cloudprofiler_v2_profilerpb.Profile)(nil)).Elem())
}
