// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_dataplex_v1_dataplexpb "cloud.google.com/go/dataplex/apiv1/dataplexpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.dataplex.v1.MetadataService", "dataplex.googleapis.com")
	method2RequestType.Store("google.cloud.dataplex.v1.MetadataService/CreateEntity", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.CreateEntityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataplex.v1.MetadataService/CreateEntity", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.Entity)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataplex.v1.MetadataService/CreatePartition", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.CreatePartitionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataplex.v1.MetadataService/CreatePartition", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.Partition)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataplex.v1.MetadataService/DeleteEntity", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.DeleteEntityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataplex.v1.MetadataService/DeleteEntity", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataplex.v1.MetadataService/DeletePartition", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.DeletePartitionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataplex.v1.MetadataService/DeletePartition", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataplex.v1.MetadataService/GetEntity", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.GetEntityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataplex.v1.MetadataService/GetEntity", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.Entity)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataplex.v1.MetadataService/GetPartition", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.GetPartitionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataplex.v1.MetadataService/GetPartition", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.Partition)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataplex.v1.MetadataService/ListEntities", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.ListEntitiesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataplex.v1.MetadataService/ListEntities", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.ListEntitiesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataplex.v1.MetadataService/ListPartitions", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.ListPartitionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataplex.v1.MetadataService/ListPartitions", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.ListPartitionsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.dataplex.v1.MetadataService/UpdateEntity", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.UpdateEntityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.dataplex.v1.MetadataService/UpdateEntity", reflect.TypeOf((*google_cloud_dataplex_v1_dataplexpb.Entity)(nil)).Elem())
}
