// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_gkehub_v1beta_servicepb "google.golang.org/genproto/googleapis/cloud/gkehub/v1beta"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.gkehub.v1beta.GkeHub", "gkehub.googleapis.com")
	method2RequestType.Store("google.cloud.gkehub.v1beta.GkeHub/CreateFeature", reflect.TypeOf((*google_cloud_gkehub_v1beta_servicepb.CreateFeatureRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1beta.GkeHub/CreateFeature", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1beta.GkeHub/DeleteFeature", reflect.TypeOf((*google_cloud_gkehub_v1beta_servicepb.DeleteFeatureRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1beta.GkeHub/DeleteFeature", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1beta.GkeHub/GetFeature", reflect.TypeOf((*google_cloud_gkehub_v1beta_servicepb.GetFeatureRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1beta.GkeHub/GetFeature", reflect.TypeOf((*google_cloud_gkehub_v1beta_servicepb.Feature)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1beta.GkeHub/ListFeatures", reflect.TypeOf((*google_cloud_gkehub_v1beta_servicepb.ListFeaturesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1beta.GkeHub/ListFeatures", reflect.TypeOf((*google_cloud_gkehub_v1beta_servicepb.ListFeaturesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.gkehub.v1beta.GkeHub/UpdateFeature", reflect.TypeOf((*google_cloud_gkehub_v1beta_servicepb.UpdateFeatureRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.gkehub.v1beta.GkeHub/UpdateFeature", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
