// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_api_cloudquotas_v1_cloudquotaspb "cloud.google.com/go/cloudquotas/apiv1/cloudquotaspb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.api.cloudquotas.v1.CloudQuotas", "cloudquotas.googleapis.com")
	method2RequestType.Store("google.api.cloudquotas.v1.CloudQuotas/CreateQuotaPreference", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.CreateQuotaPreferenceRequest)(nil)).Elem())
	method2ResponseType.Store("google.api.cloudquotas.v1.CloudQuotas/CreateQuotaPreference", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.QuotaPreference)(nil)).Elem())
	method2RequestType.Store("google.api.cloudquotas.v1.CloudQuotas/GetQuotaInfo", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.GetQuotaInfoRequest)(nil)).Elem())
	method2ResponseType.Store("google.api.cloudquotas.v1.CloudQuotas/GetQuotaInfo", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.QuotaInfo)(nil)).Elem())
	method2RequestType.Store("google.api.cloudquotas.v1.CloudQuotas/GetQuotaPreference", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.GetQuotaPreferenceRequest)(nil)).Elem())
	method2ResponseType.Store("google.api.cloudquotas.v1.CloudQuotas/GetQuotaPreference", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.QuotaPreference)(nil)).Elem())
	method2RequestType.Store("google.api.cloudquotas.v1.CloudQuotas/ListQuotaInfos", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.ListQuotaInfosRequest)(nil)).Elem())
	method2ResponseType.Store("google.api.cloudquotas.v1.CloudQuotas/ListQuotaInfos", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.ListQuotaInfosResponse)(nil)).Elem())
	method2RequestType.Store("google.api.cloudquotas.v1.CloudQuotas/ListQuotaPreferences", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.ListQuotaPreferencesRequest)(nil)).Elem())
	method2ResponseType.Store("google.api.cloudquotas.v1.CloudQuotas/ListQuotaPreferences", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.ListQuotaPreferencesResponse)(nil)).Elem())
	method2RequestType.Store("google.api.cloudquotas.v1.CloudQuotas/UpdateQuotaPreference", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.UpdateQuotaPreferenceRequest)(nil)).Elem())
	method2ResponseType.Store("google.api.cloudquotas.v1.CloudQuotas/UpdateQuotaPreference", reflect.TypeOf((*google_api_cloudquotas_v1_cloudquotaspb.QuotaPreference)(nil)).Elem())
}
