// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_assuredworkloads_v1beta1_assuredworkloadspb "cloud.google.com/go/assuredworkloads/apiv1beta1/assuredworkloadspb"
	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService", "assuredworkloads.googleapis.com")
	method2RequestType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/AnalyzeWorkloadMove", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.AnalyzeWorkloadMoveRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/AnalyzeWorkloadMove", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.AnalyzeWorkloadMoveResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/CreateWorkload", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.CreateWorkloadRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/CreateWorkload", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/DeleteWorkload", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.DeleteWorkloadRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/DeleteWorkload", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/GetWorkload", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.GetWorkloadRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/GetWorkload", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.Workload)(nil)).Elem())
	method2RequestType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/ListWorkloads", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.ListWorkloadsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/ListWorkloads", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.ListWorkloadsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/RestrictAllowedResources", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.RestrictAllowedResourcesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/RestrictAllowedResources", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.RestrictAllowedResourcesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/UpdateWorkload", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.UpdateWorkloadRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService/UpdateWorkload", reflect.TypeOf((*google_cloud_assuredworkloads_v1beta1_assuredworkloadspb.Workload)(nil)).Elem())
}
