// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_visionai_v1alpha1_lva_servicepb "google.golang.org/genproto/googleapis/cloud/visionai/v1alpha1"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics", "visionai.googleapis.com")
	method2RequestType.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics/CreateAnalysis", reflect.TypeOf((*google_cloud_visionai_v1alpha1_lva_servicepb.CreateAnalysisRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics/CreateAnalysis", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics/DeleteAnalysis", reflect.TypeOf((*google_cloud_visionai_v1alpha1_lva_servicepb.DeleteAnalysisRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics/DeleteAnalysis", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics/GetAnalysis", reflect.TypeOf((*google_cloud_visionai_v1alpha1_lva_servicepb.GetAnalysisRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics/GetAnalysis", reflect.TypeOf((*google_cloud_visionai_v1alpha1_lva_servicepb.Analysis)(nil)).Elem())
	method2RequestType.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics/ListAnalyses", reflect.TypeOf((*google_cloud_visionai_v1alpha1_lva_servicepb.ListAnalysesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics/ListAnalyses", reflect.TypeOf((*google_cloud_visionai_v1alpha1_lva_servicepb.ListAnalysesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics/UpdateAnalysis", reflect.TypeOf((*google_cloud_visionai_v1alpha1_lva_servicepb.UpdateAnalysisRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.visionai.v1alpha1.LiveVideoAnalytics/UpdateAnalysis", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
