// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_cloud_security_privateca_v1_privatecapb "cloud.google.com/go/security/privateca/apiv1/privatecapb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.security.privateca.v1.CertificateAuthorityService", "privateca.googleapis.com")
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ActivateCertificateAuthority", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ActivateCertificateAuthorityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ActivateCertificateAuthority", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/CreateCaPool", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.CreateCaPoolRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/CreateCaPool", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/CreateCertificate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.CreateCertificateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/CreateCertificate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.Certificate)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/CreateCertificateAuthority", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.CreateCertificateAuthorityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/CreateCertificateAuthority", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/CreateCertificateTemplate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.CreateCertificateTemplateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/CreateCertificateTemplate", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/DeleteCaPool", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.DeleteCaPoolRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/DeleteCaPool", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/DeleteCertificateAuthority", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.DeleteCertificateAuthorityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/DeleteCertificateAuthority", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/DeleteCertificateTemplate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.DeleteCertificateTemplateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/DeleteCertificateTemplate", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/DisableCertificateAuthority", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.DisableCertificateAuthorityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/DisableCertificateAuthority", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/EnableCertificateAuthority", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.EnableCertificateAuthorityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/EnableCertificateAuthority", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/FetchCaCerts", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.FetchCaCertsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/FetchCaCerts", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.FetchCaCertsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/FetchCertificateAuthorityCsr", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.FetchCertificateAuthorityCsrRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/FetchCertificateAuthorityCsr", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.FetchCertificateAuthorityCsrResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/GetCaPool", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.GetCaPoolRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/GetCaPool", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.CaPool)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/GetCertificate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.GetCertificateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/GetCertificate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.Certificate)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/GetCertificateAuthority", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.GetCertificateAuthorityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/GetCertificateAuthority", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.CertificateAuthority)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/GetCertificateRevocationList", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.GetCertificateRevocationListRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/GetCertificateRevocationList", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.CertificateRevocationList)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/GetCertificateTemplate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.GetCertificateTemplateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/GetCertificateTemplate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.CertificateTemplate)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ListCaPools", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ListCaPoolsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ListCaPools", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ListCaPoolsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ListCertificateAuthorities", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ListCertificateAuthoritiesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ListCertificateAuthorities", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ListCertificateAuthoritiesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ListCertificateRevocationLists", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ListCertificateRevocationListsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ListCertificateRevocationLists", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ListCertificateRevocationListsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ListCertificateTemplates", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ListCertificateTemplatesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ListCertificateTemplates", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ListCertificateTemplatesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ListCertificates", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ListCertificatesRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/ListCertificates", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.ListCertificatesResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/RevokeCertificate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.RevokeCertificateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/RevokeCertificate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.Certificate)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UndeleteCertificateAuthority", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.UndeleteCertificateAuthorityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UndeleteCertificateAuthority", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UpdateCaPool", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.UpdateCaPoolRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UpdateCaPool", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UpdateCertificate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.UpdateCertificateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UpdateCertificate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.Certificate)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UpdateCertificateAuthority", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.UpdateCertificateAuthorityRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UpdateCertificateAuthority", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UpdateCertificateRevocationList", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.UpdateCertificateRevocationListRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UpdateCertificateRevocationList", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UpdateCertificateTemplate", reflect.TypeOf((*google_cloud_security_privateca_v1_privatecapb.UpdateCertificateTemplateRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.security.privateca.v1.CertificateAuthorityService/UpdateCertificateTemplate", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
}
