// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_phishingprotection_v1beta1_phishingprotectionpb "cloud.google.com/go/phishingprotection/apiv1beta1/phishingprotectionpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.phishingprotection.v1beta1.PhishingProtectionServiceV1Beta1", "phishingprotection.googleapis.com")
	method2RequestType.Store("google.cloud.phishingprotection.v1beta1.PhishingProtectionServiceV1Beta1/ReportPhishing", reflect.TypeOf((*google_cloud_phishingprotection_v1beta1_phishingprotectionpb.ReportPhishingRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.phishingprotection.v1beta1.PhishingProtectionServiceV1Beta1/ReportPhishing", reflect.TypeOf((*google_cloud_phishingprotection_v1beta1_phishingprotectionpb.ReportPhishingResponse)(nil)).Elem())
}
