// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_shopping_merchant_inventories_v1beta_inventoriespb "cloud.google.com/go/shopping/merchant/inventories/apiv1beta/inventoriespb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.shopping.merchant.inventories.v1beta.RegionalInventoryService", "merchantapi.googleapis.com")
	method2RequestType.Store("google.shopping.merchant.inventories.v1beta.RegionalInventoryService/DeleteRegionalInventory", reflect.TypeOf((*google_shopping_merchant_inventories_v1beta_inventoriespb.DeleteRegionalInventoryRequest)(nil)).Elem())
	method2ResponseType.Store("google.shopping.merchant.inventories.v1beta.RegionalInventoryService/DeleteRegionalInventory", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.shopping.merchant.inventories.v1beta.RegionalInventoryService/InsertRegionalInventory", reflect.TypeOf((*google_shopping_merchant_inventories_v1beta_inventoriespb.InsertRegionalInventoryRequest)(nil)).Elem())
	method2ResponseType.Store("google.shopping.merchant.inventories.v1beta.RegionalInventoryService/InsertRegionalInventory", reflect.TypeOf((*google_shopping_merchant_inventories_v1beta_inventoriespb.RegionalInventory)(nil)).Elem())
	method2RequestType.Store("google.shopping.merchant.inventories.v1beta.RegionalInventoryService/ListRegionalInventories", reflect.TypeOf((*google_shopping_merchant_inventories_v1beta_inventoriespb.ListRegionalInventoriesRequest)(nil)).Elem())
	method2ResponseType.Store("google.shopping.merchant.inventories.v1beta.RegionalInventoryService/ListRegionalInventories", reflect.TypeOf((*google_shopping_merchant_inventories_v1beta_inventoriespb.ListRegionalInventoriesResponse)(nil)).Elem())
}
