// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_aiplatform_v1_aiplatformpb "cloud.google.com/go/aiplatform/apiv1/aiplatformpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.aiplatform.v1.GenAiTuningService", "aiplatform.googleapis.com")
	method2RequestType.Store("google.cloud.aiplatform.v1.GenAiTuningService/CancelTuningJob", reflect.TypeOf((*google_cloud_aiplatform_v1_aiplatformpb.CancelTuningJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.aiplatform.v1.GenAiTuningService/CancelTuningJob", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.cloud.aiplatform.v1.GenAiTuningService/CreateTuningJob", reflect.TypeOf((*google_cloud_aiplatform_v1_aiplatformpb.CreateTuningJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.aiplatform.v1.GenAiTuningService/CreateTuningJob", reflect.TypeOf((*google_cloud_aiplatform_v1_aiplatformpb.TuningJob)(nil)).Elem())
	method2RequestType.Store("google.cloud.aiplatform.v1.GenAiTuningService/GetTuningJob", reflect.TypeOf((*google_cloud_aiplatform_v1_aiplatformpb.GetTuningJobRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.aiplatform.v1.GenAiTuningService/GetTuningJob", reflect.TypeOf((*google_cloud_aiplatform_v1_aiplatformpb.TuningJob)(nil)).Elem())
	method2RequestType.Store("google.cloud.aiplatform.v1.GenAiTuningService/ListTuningJobs", reflect.TypeOf((*google_cloud_aiplatform_v1_aiplatformpb.ListTuningJobsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.aiplatform.v1.GenAiTuningService/ListTuningJobs", reflect.TypeOf((*google_cloud_aiplatform_v1_aiplatformpb.ListTuningJobsResponse)(nil)).Elem())
}
