// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_longrunning_longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	google_maps_routeoptimization_v1_routeoptimizationpb "cloud.google.com/go/maps/routeoptimization/apiv1/routeoptimizationpb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.maps.routeoptimization.v1.RouteOptimization", "routeoptimization.googleapis.com")
	method2RequestType.Store("google.maps.routeoptimization.v1.RouteOptimization/BatchOptimizeTours", reflect.TypeOf((*google_maps_routeoptimization_v1_routeoptimizationpb.BatchOptimizeToursRequest)(nil)).Elem())
	method2ResponseType.Store("google.maps.routeoptimization.v1.RouteOptimization/BatchOptimizeTours", reflect.TypeOf((*google_longrunning_longrunningpb.Operation)(nil)).Elem())
	method2RequestType.Store("google.maps.routeoptimization.v1.RouteOptimization/OptimizeTours", reflect.TypeOf((*google_maps_routeoptimization_v1_routeoptimizationpb.OptimizeToursRequest)(nil)).Elem())
	method2ResponseType.Store("google.maps.routeoptimization.v1.RouteOptimization/OptimizeTours", reflect.TypeOf((*google_maps_routeoptimization_v1_routeoptimizationpb.OptimizeToursResponse)(nil)).Elem())
}
