// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_devtools_testing_v1_testing "google.golang.org/genproto/googleapis/devtools/testing/v1"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.devtools.testing.v1.DirectAccessService", "testing.googleapis.com")
	method2RequestType.Store("google.devtools.testing.v1.DirectAccessService/AdbConnect", reflect.TypeOf((*google_devtools_testing_v1_testing.AdbMessage)(nil)).Elem())
	method2ResponseType.Store("google.devtools.testing.v1.DirectAccessService/AdbConnect", reflect.TypeOf((*google_devtools_testing_v1_testing.DeviceMessage)(nil)).Elem())
	method2RequestType.Store("google.devtools.testing.v1.DirectAccessService/CancelDeviceSession", reflect.TypeOf((*google_devtools_testing_v1_testing.CancelDeviceSessionRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.testing.v1.DirectAccessService/CancelDeviceSession", reflect.TypeOf((*emptypb.Empty)(nil)).Elem())
	method2RequestType.Store("google.devtools.testing.v1.DirectAccessService/CreateDeviceSession", reflect.TypeOf((*google_devtools_testing_v1_testing.CreateDeviceSessionRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.testing.v1.DirectAccessService/CreateDeviceSession", reflect.TypeOf((*google_devtools_testing_v1_testing.DeviceSession)(nil)).Elem())
	method2RequestType.Store("google.devtools.testing.v1.DirectAccessService/GetDeviceSession", reflect.TypeOf((*google_devtools_testing_v1_testing.GetDeviceSessionRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.testing.v1.DirectAccessService/GetDeviceSession", reflect.TypeOf((*google_devtools_testing_v1_testing.DeviceSession)(nil)).Elem())
	method2RequestType.Store("google.devtools.testing.v1.DirectAccessService/ListDeviceSessions", reflect.TypeOf((*google_devtools_testing_v1_testing.ListDeviceSessionsRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.testing.v1.DirectAccessService/ListDeviceSessions", reflect.TypeOf((*google_devtools_testing_v1_testing.ListDeviceSessionsResponse)(nil)).Elem())
	method2RequestType.Store("google.devtools.testing.v1.DirectAccessService/UpdateDeviceSession", reflect.TypeOf((*google_devtools_testing_v1_testing.UpdateDeviceSessionRequest)(nil)).Elem())
	method2ResponseType.Store("google.devtools.testing.v1.DirectAccessService/UpdateDeviceSession", reflect.TypeOf((*google_devtools_testing_v1_testing.DeviceSession)(nil)).Elem())
}
