// Code generated by grpc-proxy/proto/cmd/codegen.go; DO NOT EDIT.

package main

import (
	"reflect"

	"github.com/zhangyunhao116/skipmap"

	google_cloud_bigquery_storage_v1beta2_storagepb "cloud.google.com/go/bigquery/storage/apiv1beta2/storagepb"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
)

func Load(service2Host *skipmap.OrderedMap[string, string], method2RequestType, method2ResponseType *skipmap.OrderedMap[string, reflect.Type]) {
	service2Host.Store("google.cloud.bigquery.storage.v1beta2.BigQueryRead", "bigquerystorage.googleapis.com")
	service2Host.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite", "bigquerystorage.googleapis.com")
	method2RequestType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryRead/CreateReadSession", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.CreateReadSessionRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryRead/CreateReadSession", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.ReadSession)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryRead/ReadRows", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.ReadRowsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryRead/ReadRows", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.ReadRowsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryRead/SplitReadStream", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.SplitReadStreamRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryRead/SplitReadStream", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.SplitReadStreamResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/AppendRows", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.AppendRowsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/AppendRows", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.AppendRowsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/BatchCommitWriteStreams", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.BatchCommitWriteStreamsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/BatchCommitWriteStreams", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.BatchCommitWriteStreamsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/CreateWriteStream", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.CreateWriteStreamRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/CreateWriteStream", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.WriteStream)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/FinalizeWriteStream", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.FinalizeWriteStreamRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/FinalizeWriteStream", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.FinalizeWriteStreamResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/FlushRows", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.FlushRowsRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/FlushRows", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.FlushRowsResponse)(nil)).Elem())
	method2RequestType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/GetWriteStream", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.GetWriteStreamRequest)(nil)).Elem())
	method2ResponseType.Store("google.cloud.bigquery.storage.v1beta2.BigQueryWrite/GetWriteStream", reflect.TypeOf((*google_cloud_bigquery_storage_v1beta2_storagepb.WriteStream)(nil)).Elem())
}
